package com.mariadb.adapter.columnstorebulkconnector.wizard;

import com.informatica.tools.adapters.ui.appsdk.wizard.NewDefaultAppDataObjectWizard;

public class ColumnStoreBulkConnectorDataObjectWizard extends NewDefaultAppDataObjectWizard  {
    	/* 
    	 * Get adapter id  
    	 *************************************
    	 * AUTOGENERATED CODE : DO NOT CHANGE
    	 */
    	@Override
    	protected String getAdapterId() {
    		return "com.mariadb.adapter.columnstorebulkconnector";
    	}

}