package com.mariadb.adapter.columnstorebulkconnector.licensechecker;

import com.informatica.sdk.common.license.InformaticaLicenseChecker;
import com.informatica.sdk.common.license.PluginLicenseChecker;

public class ColumnStoreBulkConnectorLicenseChecker  implements PluginLicenseChecker {


    /**
     * This method will be called when Informatica platform does a license check on 
     * mapping object.   
     *
     * @param checker
     *  		checker object within whose scope this interface is
     *          being called. Adapter Plug-in developer can use this to participate
     *          in Informatica licensing framework.
     * @return true or false depending on whether object is licensed to run. 
     * 
     *************************************
     * AUTOGENERATED CODE : DO NOT CHANGE
     *************************************
     */

    @Override
    public boolean isLicensedToRun(InformaticaLicenseChecker checker){
    	return true;
    }


}